name: reviewdog
on: 
  pull_request:
  workflow_dispatch:
permissions: 
  pull-requests: write
jobs:
  vale:
    name: runner / vale
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Run Vale
        env:
          REVIEWDOG_GITHUB_API_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        uses: errata-ai/vale-action@reviewdog
        with:
          files: '["doc/ref_arch/kubernetes", "README.md"]'
#          reporter: github-pr-check
          reporter: github-pr-review
          token: ${{ secrets.GITHUB_TOKEN }}